server.port: 8083
spring:
  application:
    name: cloud-provider-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.9.255:3306/docker_mysql?Unicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    initialSize: 5
    minIdle: 5
    maxAdtive: 20
    validationQuery: SELECT 1 FROM DUAL

# redis
  redis:
    host: 192.168.9.255
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
# MQ
  kafka:
    # producer
    producer:
      #bootstrap-servers：连接kafka的地址，多个地址用逗号分隔
      bootstrap-servers:  192.168.9.255:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer # 序列化key的类
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

#    schema:
#      - classpath:
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

# register
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://eureka7002.com:7002/eureka
  instance:
    instance-id: user8083
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2

