server.port: 7001
eureka:
  instance:
    hostname: eureka7001.com #eureka服务地址
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
#      defaultZone: https://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka7002.com:7002/eureka
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000