server.port: 8082
spring:
  application:
    name: cloud-provider-payment
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.9.255:3306/docker_mysql?Unicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  jpa:
    database: MYSQL
    show-sql: true
    hibernate.ddl-auto: update
    properties.hibernate.dialect : org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
    properties:
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.jdbc.batch_size: 1000
    #自动建表策略
#    hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
#spring.redis.cache.clusterNodes: 127.0.0.1:6379,127.0.0.1:6380,127.0.0.1:6381,127.0.0.1:6382,127.0.0.1:6383,127.0.0.1:6384

#spring.cloud.nacos.discovery:
#  server-addr: 127.0.0.1:8848
#  enable: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8082
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2

